# Generated by Django 3.0.2 on 2020-01-13 21:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraConfig',
            fields=[
                ('camera_id', models.TextField(primary_key=True, serialize=False)),
                ('zones', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CameraPendingConfig',
            fields=[
                ('camera_id', models.TextField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('frame_url', models.TextField()),
            ],
        ),
    ]
