# Generated by Django 3.0.2 on 2020-01-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraconfig',
            name='frame_url',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
