# Generated by Django 3.0.2 on 2020-01-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cameraconfig_frame_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('incident_id', models.TextField(primary_key=True, serialize=False)),
                ('camera_id', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('video_url', models.TextField()),
            ],
        ),
    ]
