# Generated by Django 3.0.2 on 2020-01-20 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='camera_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CameraConfig'),
        ),
    ]
