# Generated by Django 3.0.2 on 2020-01-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200120_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraconfig',
            name='latitude',
            field=models.DecimalField(decimal_places=16, max_digits=22),
        ),
        migrations.AlterField(
            model_name='cameraconfig',
            name='longitude',
            field=models.DecimalField(decimal_places=16, max_digits=22),
        ),
    ]
