# Generated by Django 3.0.2 on 2020-01-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200124_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('cameras', models.ManyToManyField(related_name='alerting_groups', to='core.CameraConfig')),
            ],
        ),
    ]
