# Generated by Django 3.0.2 on 2020-01-29 10:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alertinggroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertinggroup',
            name='email_config',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='alertinggroup',
            name='sms_config',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='alertinggroup',
            name='webhook_config',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
