# Generated by Django 3.0.2 on 2020-02-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200205_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='video_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
