# Generated by Django 3.0.2 on 2020-02-28 11:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200206_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='video_url',
        ),
        migrations.AddField(
            model_name='incident',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
