# Generated by Django 3.0.2 on 2020-03-02 12:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200228_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameraconfig',
            name='alerting_mode',
        ),
        migrations.RemoveField(
            model_name='cameraconfig',
            name='alerting_mode_offset',
        ),
        migrations.RemoveField(
            model_name='cameraconfig',
            name='zones',
        ),
        migrations.CreateModel(
            name='ZoneConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('polygon', django.contrib.postgres.fields.jsonb.JSONField()),
                ('alerting_mode', models.CharField(choices=[('full', 'Full'), ('none', 'None'), ('boundary', 'Boundary')], max_length=8)),
                ('alerting_mode_offset', models.IntegerField(default=0)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='core.CameraConfig')),
            ],
        ),
    ]
