# Generated by Django 3.0.2 on 2020-03-02 12:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200302_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoneconfig',
            name='detection_types',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
