# Generated by Django 3.0.2 on 2020-03-02 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_zoneconfig_detection_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertinggroup',
            name='cameras',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='camera_id',
        ),
        migrations.AddField(
            model_name='alertinggroup',
            name='zones',
            field=models.ManyToManyField(related_name='alerting_groups', to='core.ZoneConfig'),
        ),
        migrations.AddField(
            model_name='incident',
            name='zone',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.ZoneConfig'),
            preserve_default=False,
        ),
    ]
