# Generated by Django 3.0.2 on 2020-04-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200303_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraconfig',
            name='dashboard_pass',
            field=models.TextField(blank=True, null=True),
        ),
    ]
