# Generated by Django 3.0.2 on 2020-04-28 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alertinggroup_alert_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.ZoneConfig'),
        ),
    ]
