# Generated by Django 3.0.2 on 2020-04-28 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200428_1225'),
        ('core', '0016_cameraconfig_dashboard_pass'),
    ]

    operations = [
    ]
