# Generated by Django 3.0.2 on 2020-05-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_merge_20200428_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraconfig',
            name='video_storage',
            field=models.CharField(choices=[('cloud', 'Cloud'), ('local', 'Local'), ('full', 'Full')], default='cloud', max_length=8),
        ),
    ]
